### ISSUE TITLE
Unable to specify a URL port other than 80

### ISSUE THREAD

**Issue by jjwong** [asyrjasalo/RESTinstance#10]
I am unable to set a specific port number in the URL without getting an error. I'm not very familiar with the new library, and this might not be the correct way of calling it either. Please advise on what I should do, or if this is a feature you'd like to support. Thanks!

**Error below, example url**
InvalidURL: Failed to parse: "example.com:8000" schema={ "exampled": false }

```
Library         REST       url="example.com:8000" schema={ "exampled": false }

*** Test Cases ***
Test Endpoint
   GET    /fakeusers
```

**Comment by jjwong** [comment]
Not an issue, by using quotes around the url, you are essentially adding that to the url.

**Comment by ec-wagner** [comment]
@jjwong  

Githubs's markdown syntax supports Robot Framework code blocks

```robotframework
Library         REST       url=http://example.com:8000

*** Test Cases ***
Test Endpoint
   GET    /fakeusers
```

Start Robot code block with
` ```robotframework `

and finish with
` ``` `

to get nice RF syntax highlighting

Just in case u didn't know ;-)
