### ISSUE TITLE
Update general documentation

### ISSUE THREAD

**Issue by JasonLSMART** [asyrjasalo/RESTinstance#101]
I have not been able to find a working example of uploading a file with POST and PUT endpoints.  If there is a working example with the library, please provide an example.

I have tried the following (unsuccessfully)...

```
    ${pathFile}    Set Variable    ${EXECDIR}/uploadfile.zip
    ${fileData}    Get Binary File    ${pathFile}
    ${fileData}    Get File    path=${pathFile}    encoding=CP437
    ${payload}    Create Dictionary    file=${fileData}

    ${header}    Create Dictionary    Content-Type=multipart/form-data    Accept=application/json
    Set Headers    ${header}
    POST    files/upload    body=${payload}

```

**Comment by frankbryden** [comment]
I assume the error you are getting is a json parse error, caused by the contents of the zip file being invalid JSON.
This is caused by https://github.com/asyrjasalo/RESTinstance/blob/master/src/REST/keywords.py#L1293, which passes the body of the request (ZIP file contents in your case) to the json keyword of the request method. This will in turn convert the data, which is assumed to be a JSON string to a JSON object. The parsing fails, and the request is not made.

**Comment by asimell** [comment]
@JasonLSMART https://github.com/asyrjasalo/RESTinstance/pull/113 added support for adding `data` as an arugment to `POST` and `PUT` keywords, which is the same as `--data` in `curl`. The `body` supports only JSON, but `data` should support binary data as wel. Does this help?

**Comment by JasonLSMART** [comment]
Yes, if a working example can be documented, it would help.  Thanks!
________________________________

**Comment by asimell** [comment]
@JasonLSMART I use this functionality in my current project like this

```
Get Certificate
    # ...
    # Calls a keyword that uses openssl to create a file called file.csr
   # ...
    Post    <endpoint>    data=file.csr    headers={..., "Content-Type": "application/pkcs10"}
```

**Comment by paultop6** [comment]
I also have interest in this.  Ive been struggling to get a multipart form file upload to work with both RequestLibrary and RESTInstance.  There is very little clear information from with library on how to do this.  Im using RESTInstance for all my REST testing in robot at the moment so would prefer a solution here.

**Comment by paultop6** [comment]
> @JasonLSMART I use this functionality in my current project like this
> 
> ```
> Get Certificate
>     # ...
>     # Calls a keyword that uses openssl to create a file called file.csr
>     # ...
>     Post    <endpoint>    data=file.csr    headers={..., "Content-Type": "application/pkcs10"}
>     ${cert}=    Output    response body
>     # Do stuff with ${cert}
> ```

Is this a stand alone example?  Or does it require other code to work as is?

**Comment by asimell** [comment]
We're combining multiple similar documentation related issues to this one. Thus renamed this to better cover all fields.

Currently in the scope of this ticket:
- Using files as parameters
- How to properly use validation keywords
