### ISSUE TITLE
Please support inputting non-json file

### ISSUE THREAD

**Issue by jadezhong** [asyrjasalo/RESTinstance#104]
Refer to https://asyrjasalo.github.io/RESTinstance/, in "Input" section, it only support file in json format, but in some case we need non-json file, so please support it ASAP, thx~

**Comment by asimell** [comment]
@jadezhong https://github.com/asyrjasalo/RESTinstance/pull/113 added support to add `data` to `GET`, `POST`, `PUT` and `PATCH` keywords. This is similar to `--data` flag when you use `curl` where you can add non-JSON data. Does this fix your need?

**Comment by asimell** [comment]
Closing issue due to lack of new information. Please reopen if still an issue.

**Comment by jadezhong** [comment]
> @jadezhong #113 added support to add `data` to `GET`, `POST`, `PUT` and `PATCH` keywords. This is similar to `--data` flag when you use `curl` where you can add non-JSON data. Does this fix your need?

yes, thx
