### ISSUE TITLE
Can not use DELETE with body

### ISSUE THREAD

**Issue by drvgao** [asyrjasalo/RESTinstance#106]
I see there is an issue with closed status, however as mentioned in that request I've real-world scenario where I need to send the body with a DELETE request.

Scenario:
- Create a user token with oAuth
- after completing the action, delete the token with body.

**Comment by asimell** [comment]
@drvgao https://github.com/asyrjasalo/RESTinstance/pull/113 added support for `body` in the `Delete` keyword. Does that fix your issue?

**Comment by asimell** [comment]
Closing issue due to lack of new information. Please reopen if still an issue.
