### ISSUE TITLE
Is it possible to assert the array values using Array keyword.

### ISSUE THREAD

**Issue by Mario-P** [asyrjasalo/RESTinstance#108]
Lets assume that we have the following response:
{
    "numbers": [1, 2, 3, 4]
}

Is it possible to verify the value of numbers array using:
Array    $.numbers

What shall be put then in the enum field?

What if in the response we will have array of arrays:
{
    "numbers": [[1,2,3], [2], [3], [4]]
}

**Comment by asimell** [comment]
This seems like a duplicate of #67 and #68. Closing the issue, let's continue discussion there.
