### ISSUE TITLE
POST payload as other data type?

### ISSUE THREAD

**Issue by Soravit-Saiwong** [asyrjasalo/RESTinstance#112]
Is there a way to send POST with a different data type rather than the three documented value which are json object, file or a dict. 
The endpoint that I'm testing require the payload to be a string, for example this is what I am sending via normal POST request in Python.

`dataset = "dataset={ "Name" : "MyName!"}"
`
The body is required to be a string by the endpoint. But POST in RESTinstance is verifying the payload before being sent out, I would like this to be disable.

Is there a way to send anything on post? Just like python requests library?

**Comment by asimell** [comment]
@Soravit-Saiwong https://github.com/asyrjasalo/RESTinstance/pull/113 added support for `data` argument for `POST` keyword, which is similar functionality as `--data` flag in `curl`. Does this help?

**Comment by asimell** [comment]
Closing issue due to lack of new information. Please reopen if still an issue.
