### ISSUE TITLE
[Question] How to enable request and response log in http method?

### ISSUE THREAD

**Issue by 4nif** [asyrjasalo/RESTinstance#118]
Hi

Is it possible to enable request and response log for each http method (POST, GET, PUT, etc) in Robotframework report?

I know I can use `Output` keyword, but I'll have to add this keyword on every HTTP method that I use in the test cases.
Is it possible to enable request and response by default in robotframework report?

Thanks

**Comment by Atihinen** [comment]
You could either create own testlibrary (http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#extending-robot-framework) that will extend to RESTinstance, or create keyword that will take the request keyword as an argument and then run the output after that one.

**Comment by asimell** [comment]
As a follow up, this is somewhat implemented with https://github.com/asyrjasalo/RESTinstance/issues/85 and is on the scope for release 1.2, which we are hopefully releasing in the upcoming weeks.

**Comment by 4nif** [comment]
Thanks @asimell, looking forward for the new release.

**Comment by asimell** [comment]
1.2.0 has been released with #85 implementation. We're aware it's not exactly what you asked, but please check if that fulfills your needs. I'm closing the issue for now, but please reopen if needed.
