### ISSUE TITLE
Modify json before use in http method

### ISSUE THREAD

**Issue by tremkonzah** [asyrjasalo/RESTinstance#119]
Would be possible to do it with RESTinstance?

I have scenario creating JSON file for baseline request with a valid data i.e valid user id

I would like to use the same file, however I wan to modify this file on the fly before put them to the POST     /my/endpoint    body=my_file.json

example
I want to change id to invalid id or remove the user id from json object before sent to POST

Thanks

**Comment by asimell** [comment]
It's not possible with RESTinstance. However, you can use for example [JSONlibrary](https://robotframework-thailand.github.io/robotframework-jsonlibrary/JSONLibrary.html) to modify the JSON before you send them using RESTinstance keywords.

**Comment by asimell** [comment]
We're not adding support for this as there are multiple other ways to get the same result. The point of this library is to send and validate REST requests, not modifying JSON, so closing this issue.
