### ISSUE TITLE
How to use OpenApiSpecification yaml

### ISSUE THREAD

**Issue by ZephyrusMB** [asyrjasalo/RESTinstance#124]
Hello, 
How is it possible to use your library with an OpenAPI 3.0 Specification yaml file? 
With the following code
```
*** Settings ***
Library  REST  url=http://localhost:8080  spec=petstore_openapi.yaml

*** Variables ***
&{dict}    type=1  #not used
*** Test Cases ***
test
    REST.Get     /api/v3/openapi.json
```

I get the error 
```
test                                                                  | FAIL |
'request':
    - 'path':
        - "'type'"
```
How is it possible to use correctly the endpoint in the yaml and to pass parameters? 

I'm using https://petstore3.swagger.io/  and the yaml https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml

Thank you  

![image](https://user-images.githubusercontent.com/81178328/144879182-4be46c20-d854-4585-a1e2-c923dfb0e92e.png)

**Comment by asimell** [comment]
Hi @MatteoBellarasa

Currently OpenApi v3 is not supported, because the Python dependency required for that (`openapi-core`) is still in beta and we didn't feel confident to add a potentially unstable dependency to this library. There is an open pull request (https://github.com/eficode/RESTinstance/pull/10) about this, where you can see the discussion.

**Comment by MatteoBellarasa** [comment]
Thank you for your answer @asimell. 
What about v2? is it supported? If yes do you have any use case as example? And json format?
The only example i could find is this one https://github.com/asyrjasalo/RESTinstance/issues/34
Thank you again for your patience and support.

**Comment by asimell** [comment]
V2 is supported. You can find examples from the [atest/swagger](https://github.com/asyrjasalo/RESTinstance/tree/master/atest/swagger) directory with corresponding tests for [JSON](https://github.com/asyrjasalo/RESTinstance/blob/master/atest/spec_json.robot) and [Yaml](https://github.com/asyrjasalo/RESTinstance/blob/master/atest/spec_yaml.robot).

**Comment by dtook-nbs** [comment]
Hello.  Is there any update on the development of this? for OpenAPI v3.0.  @asimell 

Thank you.
