### ISSUE TITLE
Restore sdists on pypi

### ISSUE THREAD

**Issue by bollwyvl** [asyrjasalo/RESTinstance#127]
Thanks for `RESTInstance`! It looks like [1.3.0 added wheels](https://pypi.org/project/RESTinstance/1.3.0/#files), which are _great_ for end users of PyPI, but not downstreams. Downstream at [`conda-forge`](https://github.com/conda-forge/restinstance-feedstock) we usually try to build from source tarballs, and that was working great for [1.2.0](https://pypi.org/project/RESTinstance/1.2.0/#files). 

Would it be possible to upload an sdist for 1.3.0, or more importantly, ensure that becomes part of the future release process? For today, we can build from the github tarball, so no blocker, but it's nice to have things work in "the usual way."

Thanks again!

**Comment by Atihinen** [comment]
Hi! Thanks for the info. I'll look into this.

**Comment by Atihinen** [comment]
@bollwyvl can you now try with 1.3.0 versio again if there are needed things in place?

**Comment by bollwyvl** [comment]
Looks great downstream, thanks!
