### ISSUE TITLE
How to validate specific http header from the response?

### ISSUE THREAD

**Issue by 4nif** [asyrjasalo/RESTinstance#128]
1. Is it possible to validate specific header from the response?
2. How to validate response time from the response?

**Comment by asimell** [comment]
Hi, sorry for the delay.

1. Yes, you can query `response headers` normally. For example
     ```
    My Keyword
        Get    /api/forms/1
        ${headers}=    Output    response headers
        # Or
        String    response headers Content-Type    application/json
    ```
2. The headers typically have a `Date` key, so you can just do something like this
    ```
    My Keyword
        Get    /api/forms/1
        ${date}=    Output    response headers Date
        # Validate the time using your favourite method
    ```
