### ISSUE TITLE
When I upgrade RESTinstance 1.0.2 to 1.3.0 , Robot command is unrecognized

### ISSUE THREAD

**Issue by arundhatid** [asyrjasalo/RESTinstance#129]
On the windows platform, python version 3.9.7, robot framework version - 4.1.1

On the windows platform , python version 3.9.7, robot framework version - 4.1.1

I have RESTinstance 1.0.2. I upgraded the version using the following command
`pip install RESTinstance==1.3.0`

But when I execute the following command to run my robot test:
`robot  --exclude not_ready --include pub --outputdir reports/ --reporttitle Tests  testsuit
`
It gives me the following error:
```
[robot : The term 'robot' is not recognized as the name of a cmdlet, function, script file, or operable program. 
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ robot  --exclude not_ready --include pub --outputdir reports/ --r ...
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (robot:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException](url)

```
When I reinstall RESTinstance 1.0.2, the robot command works just fine.

In my path variable following two values are there: C:\Python39 and C:\Python39\Lib
What could be the reason? How to resolve it?

**Comment by Atihinen** [comment]
Yes we can also reproduce this one.

Current workaround is to run following commands:
```
pip uninstall robotfframework
```
and then
```
pip install robotframework
````
