### ISSUE TITLE
Support YAML files for openapi spec

### ISSUE THREAD

**Issue by Kimamisa** [asyrjasalo/RESTinstance#13]
Adding a support for loading YAML files for openapi/swagger spec would be a nice enhancement.

**Comment by asyrjasalo** [comment]
Done in https://github.com/asyrjasalo/RESTinstance/commit/07d42c2fab699a22fb6911122ae7c5fa628b1d49 and released in '1.0.0b29'.

`pip install --upgrade RESTinstance`, or whatever installation method you are using, and feel free to close this issue if this fulfills your needs 🙂.

(Noting to self, that this could be easily extended to load YAML from strings as well, similarly as loading JSON from strings is possible, but that has little practical use cases. Python yaml provides `loads` similarly as json provides `loads`)

**Comment by Kimamisa** [comment]
awesome ! Thanks.
