### ISSUE TITLE
Set log level also part of RF Builtin

### ISSUE THREAD

**Issue by Harm10** [asyrjasalo/RESTinstance#143]
I am getting a warning when using Set log level command:
`[ WARN ] Keyword 'Set Log Level' found both from a custom test library 'REST' and a standard library 'BuiltIn'. The custom keyword is used. To select explicitly, and to get rid of this warning, use either 'REST.Set Log Level' or 'BuiltIn.Set Log Level'.
[ WARN ] Unrecognized log level 'NONE'. Using default log level 'WARN'.`

Obviously I want to use the Builtin version.
Can you please change this command within RESTinstance so this problem will disappear?

**Comment by Harm10** [comment]
@asyrjasalo That is turning the world around! Builtin is core of RF so in my view no package should use keywords that are defined in there. So please reopen this issue?

**Comment by asyrjasalo** [comment]
Hi,

Our code of conduct is that we target the library for those people who are capable in turning the world around.

There is possibly some hint in the library name.

Hope this clarifies.

BR,
Anssi
Lead Developer, Robot Framework
