### ISSUE TITLE
Improvement - Add variables values in the report

### ISSUE THREAD

**Issue by harmin-parra** [asyrjasalo/RESTinstance#149]
It would be highly desirable to add variables values to the report.

The feature file:
```
*** Settings ***
Library         REST    https://petstore.swagger.io/v2/pet/

*** Variables ***
${payload}     { "id": 5432, "name": "doggie", "status": "available" }
${id}              5432


*** Test Cases ***

Add a pet
    POST    /    ${payload}
    Output schema    response body
    Integer    response status    200
    [Teardown]  Output schema
```

The report:
![image](https://github.com/user-attachments/assets/3baf0ff6-97eb-43f1-ae29-246ff05f5b6b)

I would like to see the value of the `${payload}` variable in the report.

**Comment by asyrjasalo** [comment]
The report is not created by RESTinstance but by RF.

Kindly open the improvement there.

I like your suggestion.

**Comment by harmin-parra** [comment]
Are you 100% sure about that ?

Because when I use the selenium plugin, I do have the variables values in the report.

![image](https://github.com/user-attachments/assets/eca71043-6c65-40a3-81cf-d41a9f8bfc2f)

**Comment by asyrjasalo** [comment]
100% sure.

Thank you for your effort.
