### ISSUE TITLE
Keyword documentation

### ISSUE THREAD

**Issue by Atihinen** [asyrjasalo/RESTinstance#2]
Please generate keyword documentation with libdoc (http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#libdoc) for the library, thanks

**Comment by asyrjasalo** [comment]
Yes, the keyword documentation, as well as a README describing the [REST API testing] problems and the solutions, use cases and crediting the contributors, are to be part of 1.0.0 (final), which is to be released by the end of February 2018. Meanwhile, your best user guide may be the library's tests itself: https://github.com/asyrjasalo/RESTinstance/tree/master/tests.
