### ISSUE TITLE
Question regarding Kerberos authentication

### ISSUE THREAD

**Issue by pingjie89** [asyrjasalo/RESTinstance#21]
Hi, 

My problem is on my request server is using Kerberos authentication.

I tried to do _**| | Set Headers | { "Authorization" : "Negotiate"} |**_
Was trying to do something similar like what was successfully run using curl _**curl --negotiate -u : -X GET "url"**_

Searched around the documentation and didn't find any solution/documentation regarding this item

By using curl --negotiate -u : verbose,
I can see:

curl send request and return response is **_401, www-authenticate: negotiate_**
curl send request with **_"Authorization" : "Negotiate {$kerberostoken}"_** and return response 200, with body result

**Comment by asyrjasalo** [comment]
Hi,

`| Set headers | { "Authorization": "Negotiate ${kerberostoken}" } |` does not work?

**Comment by pingjie89** [comment]
Unfortunately no, as not very well versed with HTTP security mechanism. Not sure what happened in background.

But I was able to do authenticate through request-kerberos library follow their documentation. 

As the change I did in https://github.com/asyrjasalo/RESTinstance/pull/23

**Comment by pingjie89** [comment]
Following the example of [request-kerberos](https://github.com/requests/requests-kerberos), I only able to get status code 200 when I use the OPTIONAL flag like `kerberos_auth = HTTPKerberosAuth(mutual_authentication=**OPTIONAL**)`

REQUIRED and DISABLED was failed to work.

**Comment by Atihinen** [comment]
Since this requires external dependency we're not going to implement this right now due to fact that there hasn't been any new requests to support kerberos after 2018. We found that there is Apple supported python library for this purposes https://pypi.org/project/kerberos/. Please re-create issue or pr if there is still the need for this.
