### ISSUE TITLE
For content type - application/x-www-form-urlencoded, it always says "Missing grant_type parameter value"

### ISSUE THREAD

**Issue by karthiksml** [asyrjasalo/RESTinstance#24]
For content type - application/x-www-form-urlencoded, it always says "Missing grant_type parameter value"

Do we have any way to post "application/x-www-form-urlencoded" content types. 

{"Content-Type": "application/x-www-form-urlencoded}
grant_type=password&username=test%40test.com&password=test%40018&scope=openid&tenantDomain=test.com

Output:
{
    "error_description": "Missing grant_type parameter value",
    "error": "invalid_request"
}

Please suggest

**Comment by asyrjasalo** [comment]
Could you post the test case here where you are trying this?

**Comment by karthiksml** [comment]
we are trying to create access token with an API call in our application.

Scenario:
Set Headers        {"content-type": "application/x-www-form-urlencoded", "Authorization": "Bearer Y1hXTzNRWlMzQVRmWEpQa1BjS2pFTjg4MGk4YTpjVjVRQk5yVWUyN2M2QXBfQ2lyWllpbmRZeEl"}
Post       /token      grant_type=password&username=test@test.com&password=test@123&scope=openid&tenantDomain=test.com
Output    response body

Result:
{
"error_description": "Missing grant_type parameter value",
"error": "invalid_request"
}

am i missing anything here. I couldn't give u the actual data due to organization norms.

pls help me out here

**Comment by asyrjasalo** [comment]
I haven't tested with this `Content-Type`. The focus of this library is about testing JSON APIs - I am happy to review and recommend if anyone forks the library for any other purpose.
