### ISSUE TITLE
 clear expectations doesn't clear spec that inserted in expect spec

### ISSUE THREAD

**Issue by JanneKoistinenQFactory** [asyrjasalo/RESTinstance#26]
I have a test suite where I have example
```
*** Settings ***
Test Setup          Expect spec                     API_spec.json

*** Test Cases ***
example case 1
        GET     api_query_to_path

example case 2
        GET   api_query_to_path
       Clear Expectations
       GET   query_that_path_doesn't_found from_spec

example case 3
      Expect Spec     spec={}   replace=true
       GET   query_that_path_doesn't_found from_spec

```

Case 1 and 3 PASS

Case 2 gives   FAIL
u'request':
    - 'path':
        - 'No paths found for path_that_doesn't_exist'

Question?
Should `'Clear Expectations'` to do same as `'Expect Spec     spec={}   replace=true'` does ?

**Comment by jjwong** [comment]
Getting similar issue. It looks like `Clear Expectations` was working at one point, but it no longer clears  expectations. This causes test cases to "bleed" into each other.

**Comment by asyrjasalo** [comment]
Removed keyword `Expect spec` in >1.0.0rc1, as this was confusing. Set `spec` in the library init and use `validate=false` in HTTP keywords to skip validations if necessary.
