### ISSUE TITLE
did not match anything when using jsonpath in an object

### ISSUE THREAD

**Issue by virtualnode** [asyrjasalo/RESTinstance#30]
*** Settings ***
Library         REST                    https://jsonplaceholder.typicode.com

*** Test Cases ***
JSONPath query from object
    GET         /users/1
    ${root}=    Object       $  
    ${o_lng}=     String          $.address.geo.lng
    ${lng}=    Set Variable     ${o_lng[0]}
    ${somegeo}=    Object      $.address.geo[?(@.lng\\='${lng}')]

**Comment by asyrjasalo** [comment]
Did not understand any of this, closing.
