### ISSUE TITLE
how to test api aganist   SWAGGER spec?

### ISSUE THREAD

**Issue by McDingl** [asyrjasalo/RESTinstance#31]
i test your e.g  ,but error  ::

1.FAIL : No keyword with name 'DELETE' found;
2.how to import "Resource          resources/mounterest.robot"
3.what is that mean ?  "Library           REST    mounterest:${api_port}/"      what is  mounterest????
4.how to relate the  swagger file?

thank you !

**Comment by asyrjasalo** [comment]
Did not understand any of this, closing.
