### ISSUE TITLE
Multipart post example ?

### ISSUE THREAD

**Issue by rgarrigue** [asyrjasalo/RESTinstance#32]
Hi

I've a third party so called API poorly made to say the least. Would you be kind enought to provide an example about how to do multipart post ? I generated this python request snippet using my REST client (Insomnia), but I can't transcript it properly to robot / RESTinstance.

```
import requests

url = "http://192.168.60.10/api/index.php"

payload = "-----011000010111000001101001\r\nContent-Disposition: form-data; name=\"username\"\r\n\r\nadmin"
headers = {'content-type': 'multipart/form-data; boundary=---011000010111000001101001'}

response = requests.request("POST", url, data=payload, headers=headers)

print(response.text)
```

Thanks & regards,

**Comment by asyrjasalo** [comment]
I don't think testing any other `Content-Type` than JSON is the focus of this test library - my goal is to keep things simple - but I am happy to review and recommend if anyone forks the library for that purpose.
