### ISSUE TITLE
test  by  swagger spec is useless？？？？

### ISSUE THREAD

**Issue by McDingl** [asyrjasalo/RESTinstance#33]
1.  input spec  file  could  not same as  the code logic , so input spec is  not essential!

eg:    if i  modify  the spec file  content    ,  but  api respone the correct fromat , 
       the spec content  only use  in   output  instance file  before   request and respone josn node ,
     but they not corresponding!!!

**Comment by asyrjasalo** [comment]
Did not understand any of this, closing.
