### ISSUE TITLE
Expect Response kw seems not to validate the content of inputted Json file

### ISSUE THREAD

**Issue by DoanhPoPu** [asyrjasalo/RESTinstance#35]
I'm going to parse the requests as well as inputted json file to compare the content.

Thanks,
Doanh Nguyen

**Comment by asyrjasalo** [comment]
Did not understand any of this, closing.

**Comment by DoanhPoPu** [comment]
@keyword
    def expect_response_body(self, actual, expected):
        with open(expected) as f:
            expected = json.load(f)
        print actual['list'][0]
        print expected['list'][0]
        for key in expected['list'][0].keys():
            if key in actual['list'][0]:
                return True
            else:
                raise AssertionError("Not Matching")

@asyrjasalo Hope you can have time to review this method (I'm a tester and new in python). Any comments are much appreciated :)

**Comment by asyrjasalo** [comment]
If you want to assert that the responded body JSON matches the expected JSON, use keyword `Object` or `Array`, depending on whether an object or an array is expected to be returned. An example of this (with an array) is at https://github.com/asyrjasalo/RESTinstance/blob/master/tests/methods.robot#L28. 

Keyword `Expect response` is used to validate that the responded JSON (body, status, etc.) passes against a JSON Schema. For examples, see the tests at https://github.com/asyrjasalo/RESTinstance/blob/master/tests/schema.robot and the actual JSON Schema used by those tests at https://github.com/asyrjasalo/RESTinstance/blob/master/tests/schemas/valid/response.json.

Hopefully these examples help a bit.

**Comment by DoanhPoPu** [comment]
Thanks so much for your comments. I extended your lib and defined some custom kws for my project :)
