### ISSUE TITLE
SSL certificate verify failed

### ISSUE THREAD

**Issue by karezza** [asyrjasalo/RESTinstance#36]
I'm working against a server with a self-signed certificate in a DEV environment.  How do I keep the test from failing for this reason?  An additional example with this would be good.  Also one specifying headers.

GET to https://hidden.com/pathto SSL certificate verify failed:
HTTPSConnectionPool(host='hidden.com', port=443): Max retries exceeded with url: /pathto (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)'),))

**Comment by parthvyas88** [comment]
I am facing same issue for simple GET request working with open public apis https://api.publicapis.org/entries?category=animals&https=true

**Comment by BrianSidebotham** [comment]
In order to get around this, you can import with the `ssl_verify` setting set to `false`:

```
Library           REST      ssl_verify=false
```
