### ISSUE TITLE
facing problem to get response i.e. authentication key and get other response and store in a variable

### ISSUE THREAD

**Issue by prajaktam** [asyrjasalo/RESTinstance#38]
Hi Team,
I am exploring RESTinstance, no prior experience in API test using Robot Framework so facing problem to get response i.e. authentication key and get other response and store in a variable.

Below is my dummy code .. it is not confidential:

```
*** Settings ***
Library         REST      https://xxxxxxxxxxxxxxx.in/
Suite Setup     Set Expectations

*** Keywords ***
Set Expectations
    Expect response     {"status":{"enum":[200, 201, 204, 401,405, 500]}}
    Expect response     {"seconds":{"maximum":1.5}}
*** Variables ***
${json}         { "email": "xxxxxxxx@xxxxx.com",   "password": "password" }

*** Test Cases ***
POST with valid params to create a user
    POST        /api-token-auth/          ${json}
    Integer     response status           200
    #[Teardown]  Output                    file_path=${OUTPUTDIR}/inst.json
    Output      response body   
```

Can you please help correct me, as I am not understanding how to implement.

and one more thing, I want to get a response from one request and from that response few information need to pass on to another request body. How can I do that?

**Comment by Atihinen** [comment]
Hi,

You can use `Output` keyword for this.

e.g.
`${token}=     Output    response body accessKey`
