### ISSUE TITLE
Does REST support POST with x-www-form-urlencoded?

### ISSUE THREAD

**Issue by allenorac** [asyrjasalo/RESTinstance#39]
Hi, 

Does REST support POST with Content-Type/x-www-form-urlencoded and encoded data?

**Comment by asyrjasalo** [comment]
I haven't tested posting with this `Content-Type`. The main focus of the library is, and is to be, JSON APIs.

**Comment by ec-wagner** [comment]
But I have tested. See question #45

@allenorac 
RESTInstance does not support POST with Content-Type/x-www-form-urlencoded headers - yet.

But I know that [robotframework-requests](https://github.com/bulkan/robotframework-requests) does.
It would be greate to add this feature to this library, too.
