### ISSUE TITLE
Responses

### ISSUE THREAD

**Issue by rakkyno** [asyrjasalo/RESTinstance#46]
hello, can you add example testcases for working with responses? i have a problem when i want to work with body response. thank you. i really appreciate your work.

**Comment by asyrjasalo** [comment]
At the some point in the future, yes.

And thanks! As the current development process is "when I have free time", I do not promise any deadlines. What I can promise though is to help with pull requests better than I have done in the past.

**Comment by Atihinen** [comment]
We're now closing this issue since there is `atest` folder that contain working example test cases. Reopen / recreate the issue if more specific examples documentation is needed. :)
