### ISSUE TITLE
Readme is not clear and running the docker command fails

### ISSUE THREAD

**Issue by sgandon** [asyrjasalo/RESTinstance#48]
the docker command 
```
docker run --rm -ti --env HOST_UID=$(id -u) --env HOST_GID=$(id -g) \
  --env HTTP_PROXY --env HTTPS_PROXY --network host \
  --volume "$PWD/tests":/home/robot/tests \
  --volume "$PWD/results":/home/robot/results \
  asyrjasalo/restinstance tests
```
fails and it is expected if the test docker images (mountrest... )are not also launched but this is not clear in the readme.

**Comment by asyrjasalo** [comment]
Fixed by https://github.com/asyrjasalo/RESTinstance/commit/fff3d41d426f07061c61ef85eac2ca0b698e5c0c
