### ISSUE TITLE
Remove strict versioning from requirements.txt

### ISSUE THREAD

**Issue by SergeySerj** [asyrjasalo/RESTinstance#53]
Hi,

I noticed I'm unable to add this library to my project via pipenv due to 'incompatible versions in the resolved dependencies' pipenv error.
This happens because some library vendors sticks to strict versions in their requirements.txt file like this:
```
requests==2.20.0
requests-oauthlib==1.0.0
```
Therefore if one library needs `requests==2.20.0` while another library needs `requests==2.12.4` then pipenv would be unable to satisfy those conditions.

Could we have a more relaxed versions specification, like the next example?
```
requests>=2.20.0
```
The same goes for other libraries within requirements.txt.

Thanks.

**Comment by asyrjasalo** [comment]
Yeah, this is some legacy, I was not too skilled on Python (virtual)envs back when I started this library.

Will incorporate the tooling here I just released at https://github.com/Omenia/libcutter, maybe other test library developers can benefit from these as well. Moreover, striving to tackle some long-persisting issues in Python packaging - hopefully without totally reinventing wheel(s) but at the same time keeping the options open for `pipenv` and `poetry` as well. :+1:

**Comment by rezende** [comment]
I'd ask if `pytz` can be also unlocked from versioning.

**Comment by stdedos** [comment]
also `pygments`:
```python
restinstance 1.0.0 has requirement pygments==2.3.1, but you'll have pygments 2.4.2 which is incompatible.
restinstance 1.0.0 has requirement requests==2.21.0, but you'll have requests 2.22.0 which is incompatible.
```

**Comment by asyrjasalo** [comment]
Done in 1.0.2.
