### ISSUE TITLE
post need `params` argument

### ISSUE THREAD

**Issue by kanchi240** [asyrjasalo/RESTinstance#54]
Hi,

My api post use `Parameters` to send data, but `post` keyword not have the argument, so I need to add all the params to the endpoint.

**Comment by luminatory** [comment]
@asyrjasalo, will the requested 'Parameters' be implemented? 
I have come across the same issue. I cannot send auth data via headers or body

**Comment by ravthiru** [comment]
@asyrjasalo how to send "x-www-form-urlencoded" data to POST 
Something like this in Python
 d = {'banana': 20, 'eggs': 3}
>>> requests.post("http://localhost:8080", data=d)

**Comment by Atihinen** [comment]
Hi!

Does the pull request #99 fix the issue?
