### ISSUE TITLE
Getting "SchemaGenerationError: Could not find matching type for object: 1549286611000L" for GET,POST call

### ISSUE THREAD

**Issue by deepakg4all** [asyrjasalo/RESTinstance#58]
Hi, 
Getting "SchemaGenerationError: Could not find matching type for object: 1549286611000L" for most of my GET and POST call. Observed when JSON response is large. Also, same call executed successfully via POSTMAN and REST-ASSURED. 
System details : 
OS : Windows 10 
robotframework==3.1.1
Pygments==2.2.0
wxPython= 2.8 (32 bit)
robotframework-ride==1.5.2.1
Python =2.7 
I saw same issue has closed without much details https://github.com/asyrjasalo/RESTinstance/issues/37. So appreciate your help on this.

**Comment by Atihinen** [comment]
https://github.com/asyrjasalo/RESTinstance/issues/37#issuecomment-448822159

So yeah the issue is for using 2.7. Upgrade to latest python3 (also python2 is now dead).
