### ISSUE TITLE
Improve documentation regarding keyword args and examples

### ISSUE THREAD

**Issue by asyrjasalo** [asyrjasalo/RESTinstance#6]
- [x] Improve keyword documentation regarding arguments
- [x] Embed an example covering the library features, and as a tutorial, to README.rst
- [x] Host keyword documentation on GitHub (project) pages - https://asyrjasalo.github.io/RESTinstance

**Comment by rgarrigue** [comment]
Hi

I'm quite waiting for this one, it's hard to get around the way this library works to get started

Best regards,

**Comment by asyrjasalo** [comment]
Done. Closing.
