### ISSUE TITLE
Problems POSTing other representations than JSON

### ISSUE THREAD

**Issue by ppazos** [asyrjasalo/RESTinstance#60]
Hi, I'm testing this extension on my REST API where, as REST, supports many representations for the same resource, for POST and GET.

I was testing with other formats than JSON for POST and it seems the library is not processing them correctly.

Is this library JSON only?

**Comment by asimell** [comment]
Hi @ppazos 

This used to support JSON only, but https://github.com/asyrjasalo/RESTinstance/pull/113 added support for `data` as an argument to `Post`, `Put`, `Patch`, and `Get` keywords, which allow other forms of payloads. Does this help you?

**Comment by asimell** [comment]
Closing issue due to lack of new information. Please reopen if still an issue.
