### ISSUE TITLE
Please add more examples on how to use the enum and validations on the Array keyword

### ISSUE THREAD

**Issue by ppazos** [asyrjasalo/RESTinstance#67]
From https://asyrjasalo.github.io/RESTinstance/#Array I wasn't sure how to use enum and validations. Would be wonderful to have more examples,and maybe something comples like constraints over an array of objects. Thanks.

**Comment by Atihinen** [comment]
We've added #101 to milestone 1.3.0. I'll close this one. If you have any comments please use issue #101
