### ISSUE TITLE
Any plans to complete the examples? Only 0_ and 1_ files are available.

### ISSUE THREAD

**Issue by dan-arsenault** [asyrjasalo/RESTinstance#69]

**Comment by asimell** [comment]
Getting more examples done is definitely in the TODO pile. However, as we're quite early in taking over maintenance of this repository we're tackling actual bugs and PRs first before focusing on documentation.

**Comment by Atihinen** [comment]
We've added #101 to milestone 1.3.0. I'll close this one. If you have any comments please use issue #101
