### ISSUE TITLE
PyCharm doesn't recognize this library

### ISSUE THREAD

**Issue by ecarmiel** [asyrjasalo/RESTinstance#77]
Hi
I install using pip install the library and added to Pycharm project Interpreter (version 1.0.0) .
When i use the keywords in pycharm (like GET ,Output ) doesn't recognize them and puts red line under them
Running the robot does work and library sends requests.
is there any way to fix this ?

**Comment by Dorwald** [comment]
@ecarmiel 
Hi. 
There is "name=None" in decorator "@keyword(....)" before all keywords. I did not figure out why this was done, but erasing it helps for pyCharm and IntelliBot.
