### ISSUE TITLE
Second call of validation keyword (Integer) is ignored

### ISSUE THREAD

**Issue by Tset-Noitamotua** [asyrjasalo/RESTinstance#79]
## steps to reproduce:

```robotframework
*** Test Cases ***
Call Integer response status twice
    REST.POST    ${baseurl}/endpoint
                 Integer      response status    201  200
                 Integer      response status    400
```

## actual result:
`Integer    response status    400` seems to be completely ignored (s. screenshot)

![image](https://user-images.githubusercontent.com/5635462/61311678-2752a880-a7f7-11e9-99a6-7917b8344477.png)

## expected result:
Test should fail at last step because 400 != 201

**Comment by Atihinen** [comment]
This seems to be duplicate issue with #73 . Let's continue on there
