### ISSUE TITLE
Incompatible License?

### ISSUE THREAD

**Issue by nurikabe** [asyrjasalo/RESTinstance#89]
I think there may be a license incompatibility.

RESTinstance uses a couple of GPL3 libraries:

* https://pypi.org/project/rfc3987/
* https://pypi.org/project/strict-rfc3339/

GPL projects can include Apache-licensed work, however the Apache license is not compatible with importing GPL'd code:  https://www.apache.org/licenses/GPL-compatibility.html

**Comment by Atihinen** [comment]
Thanks for pointing it out. We will check the status and make the needed changes

**Comment by asyrjasalo** [comment]
Might have been explicit dependencies for jsonschema validator.

Closing.

**Comment by jstaffans-relex** [comment]
If there indeed is no requirement for LGPL anymore, can the project be re-licensed using Apache 2.0?

**Comment by asyrjasalo** [comment]
No. If you need more permissive license for commercial purposes you can purchase it from me.
