### ISSUE TITLE
Missing content-type in response fails test

### ISSUE THREAD

**Issue by wigledejong** [asyrjasalo/RESTinstance#90]
When sending a request, in my case a post request, to a rest service my tests fails. 

After debugging I found that the rest service has no content-type in the response header.  The code is excepting that response.header["Content-Type"] is present so the tests fails with KeyError: 'content-type'

The code responsible for this is on row nummer 1334 of keywords.py.

Could this be fixed?

**Comment by asimell** [comment]
Is this still an issue? 

Line [1334](https://github.com/asyrjasalo/RESTinstance/blob/master/src/REST/keywords.py#L1334) doesn't seem to match the root cause anymore.

**Comment by wigledejong** [comment]
Issue could be closed. It is not relevant for us anymore.
