### ISSUE TITLE
Importing test library 'REST' failed

### ISSUE THREAD

**Issue by bob-r** [asyrjasalo/RESTinstance#96]
ImportError: No module named 'jsonpath_ng.bin'; 'jsonpath_ng' is not a package

pip3 freeze:
robotframework==3.1.2
RESTinstance==1.0.2
jsonpath-ng==1.5.0

I guess, jsonpath_ng should be fixed to 1.4.3, the latest compatible version

**Comment by asimell** [comment]
Hi,

```
RESTinstance==1.1.0
jsonpath-ng==1.5.2
```
works alright in my setup. Does the error persist with that?

**Comment by asimell** [comment]
Closing issue as there is no new information. Please reopen if still an issue.
