### ISSUE TITLE
Unable to send XML payload in the form of key - value pair for a POST request in robot framework

### ISSUE THREAD

**Issue by Manisha0421** [asyrjasalo/RESTinstance#97]
Hi,

I have to make a POST request through SOAP   to a URL by providing the payload as an XML file in the form of a key value pair, like xml: "content of XML file"

The code is able to read the XML file correctly and displays the content of the file but when making the POST request, it gives "

HTTP/1.1 400 Unable to get data [ xml is required]"

Note: This request is being sent using robot framework script;
The same request is working fine with the same XML when sending the request via Postman.

Robot file code:
Create Session    soap    ${URLService}    verify=False
    ${file_data}    Get Binary File    ${Transaction_Request}
    Log    ${file_data}
    ${files}=    Create Dictionary    xml    ${file_data}
    ${headers}=    Create Dictionary    Content-Type=application/xml
    ${resp}=    Post Request    alias=soap    uri=${URLComponentDateRangeAPI}    files=${files}    headers=${headers}
    Log    ${resp.content}
    ${root}=    Parse Xml    ${resp.content}
    log    ${root.tag}

Output for POST request:

<?xml version="1.0" encoding="UTF-8"?>
			<ccare>
			<response><menu name="" ref=""></menu>
							<page title="" pageRef="">
							<table resizable="true">
							<tableHead currentPage="1" nbPages="1" nbRecords="1">
							<cell size="200" filter="no-filter"><text>ErrorMessage</text></cell>
							</tableHead>
							<tableData>
							<row><cell size="200" filter="no-filter"><text>HTTP/1.1 400 Unable to get data [ xml is required ]</text></cell></row>
						</tableData>
						</table>
						</page>
						</response>
			</ccare>

Can anybody help resolve this issue.

Thanks & Regards

**Comment by testautomation** [comment]
I had same issue in the past. POSTing xml payloads was not supported by this library - not sure if that has changed @asyrjasalo?  Use robotfamework-requestlibrary instead for sending xml.

**Comment by Atihinen** [comment]
Hi!

At the moment we don't have any plans to start support XML with RESTInstance, please use the [robotframework-requestlibrary](https://pypi.org/project/robotframework-requests/) instead for the time being.

**Comment by wlad** [comment]
@Atihinen any news on supporting XML payloads?
