### ISSUE TITLE
[Question] How to save "set-cookie" header 

### ISSUE THREAD

**Issue by crile** [asyrjasalo/RESTinstance#98]
Hi,

I fail to save the "set-cookie" header from a response to use it in a next request.
I use "REST.Output" to extract any data from the response. However, it seems that the specific header "set-cookie" is not in it.

Any advice ?

Thanks.

**Comment by asimell** [comment]
Hi @crile 

How are you trying to read it?

`${cookie}=    Output    response header set-cookie` doesn't work?

**Comment by Atihinen** [comment]
We can open a new issue if there is need for it. Closing this one for now.
